### ISSUE TITLE
Empty point

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#100]
https://dev.kohesio.linkedopendata.eu/api/facet/eu/search/project/map/point?coordinate=2.3619618733359,48.79389532427 is empty

![empty](https://user-images.githubusercontent.com/942488/151784867-e2f4e507-9ebd-49b8-955c-b488d15f3784.png)

**Comment by D063520** [comment]
it is working currently, so we cannot debug it .... please open again if it appears again

**Comment by madewild** [comment]
OK @roberto-musmeci fyi
