### ISSUE TITLE
Search API cache not regenerated

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#101]
Project https://dev.kohesio.eu/projects/Q139379 has been renamed from "MELLISEN" to "MELLISENSE".
This is already reflected both on the project fiche and in the search results. However:

https://dev.kohesio.eu/projects?keywords=MELLISENSE&sort=Budget-(descending) does not find this project

https://dev.kohesio.eu/projects?keywords=MELLISEN&sort=Budget-(descending) does still find this project

**Comment by madewild** [comment]
By the way the other project was a duplicate.

**Comment by madewild** [comment]
The problem is fixed today!! :)

https://dev.kohesio.eu/projects?tab=results&keywords=mellisen
https://dev.kohesio.eu/projects?tab=results&keywords=mellisense

@D063520 did you change something on the Lucene index? Or maybe it's linked to the fact that we are currently not using the live endpoint? Closing for now, will reopen if it reappears...

**Comment by madewild** [comment]
also working on https://kohesio.test.ec.europa.eu/projects?tab=results&keywords=mellisense :)

**Comment by D063520** [comment]
no, it is the fresh index, still we have to text with the live endpoint

**Comment by madewild** [comment]
- [ ] Test with live endpoint

**Comment by madewild** [comment]
I confirm it still works now that the live endpoint is back: https://dev.kohesio.eu/projects?tab=results&keywords=mellisense
Problem solved, closing.
