### ISSUE TITLE
Missing search results with frozen index

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio-backend#109]
In acceptance If you search 'University / Portugal' you don't have the 'University of Porto' in the results. This beneficiary exists: https://kohesio.acceptance.ec.europa.eu/beneficiaries/Q2993198 and was findable under kohesio.eu.
Is it a cache issue?
@madewild

**Comment by madewild** [comment]
I confirm the issue: https://kohesio.acceptance.ec.europa.eu/beneficiaries?name=university&country=Portugal
Compare with https://dev.kohesio.eu/beneficiaries?name=university&country=Portugal
@D063520 @raphdom  any clue why this is happening?

**Comment by madewild** [comment]
PS: the issue is not specific to ACC, it also happens on:
https://kohesio.test.ec.europa.eu/beneficiaries?name=university&country=Portugal
https://kohesio.development.ec.europa.eu/beneficiaries?name=university&country=Portugal

**Comment by madewild** [comment]
Now there is nothing at all :(
https://kohesio.acceptance.ec.europa.eu/api/facet/eu/search/beneficiaries?offset=0&limit=15&name=univ*&country=https://linkedopendata.eu/entity/Q18

**Comment by raphdom** [comment]
With the new index all the search is weird. Waiting @D063520 to debug it. All environments we apply the new index.

**Comment by D063520** [comment]
hi Raph, how can I help? I checked yesterday and the same index is working on the ec2 DEV. In fact currently if you go to the dev.kohesio.eu we are using exactly the index you took yesterday ....

**Comment by madewild** [comment]
The problem is probably that we use an outdated version of the QAnswer application... You pushed an image on February 5 but this still goes to the old ECR that is not used anymore! Sorry our fault, I sent new credentials to push to the correct ECR.

**Comment by madewild** [comment]
Now it's also missing on https://dev.kohesio.eu/beneficiaries?name=university&country=Portugal !
Cache issue?

**Comment by madewild** [comment]
With https://dev.kohesio.eu/beneficiaries?name=university%20porto&country=Portugal we find it... weird.

**Comment by madewild** [comment]
Other example:
https://kohesio.eu/beneficiaries?country=France&name=university has 2 results
https://dev.kohesio.eu/beneficiaries?country=France&name=university has no results
https://dev.kohesio.linkedopendata.eu/api/facet/eu/search/beneficiaries?offset=0&limit=15&name=university&country=https://linkedopendata.eu/entity/Q20

I checked and the two beneficiaries are still linked to valid Kohesio projects so they should be there...

**Comment by madewild** [comment]
On https://dev.kohesio.eu/beneficiaries?name=university&country=Portugal it is working again (16 results) with live endpoint
Let's make sure we deploy the same version to TEST and ACC tomorrow...

**Comment by madewild** [comment]
https://dev.kohesio.eu/beneficiaries?country=France&name=university also has the 2 expected results
the version on dev.kohesio.eu is correct (but something was wrong when we switched to the frozen index so let's be cautious)

**Comment by madewild** [comment]
Also happens for projects.
https://kohesio.test.ec.europa.eu/projects?keywords=%22school%22&sort=Total-Budget-(descending)&country=Czechia&theme=Social-Inclusion&policyObjective=Social-Europe has only 66 results (1634 in dev with live index). https://kohesio.test.ec.europa.eu/projects/Q51985 is not discoverable for instance.

**Comment by madewild** [comment]
Other side effect reported by @gachpas: https://kohesio.test.ec.europa.eu/projects?keywords=%22renewable%20energy%22&sort=Total-Budget-(descending) (with quotes) has more results than https://kohesio.test.ec.europa.eu/projects?keywords=renewable%20energy&sort=Total-Budget-(descending) (without quotes) which makes no sense
In dev with live index it works properly of course...

**Comment by madewild** [comment]
Is there a temporary quick fix by raising the limit or should I already postpone to 1.2?

**Comment by D063520** [comment]
@madewild can you check now if it is what you expect?

https://kohesio.test.ec.europa.eu/beneficiaries?name=university

**Comment by madewild** [comment]
Yes good for https://kohesio.test.ec.europa.eu/beneficiaries?name=university&country=Portugal it has 16 results like in dev!

The two other issues are not solved yet... but maybe this can wait.
https://github.com/ec-doris/kohesio-backend/issues/109#issuecomment-1043540978
https://github.com/ec-doris/kohesio-backend/issues/109#issuecomment-1046023509

**Comment by D063520** [comment]
The comment part is too heavy .... it would slow down other parts .... I prefer to keep like this

**Comment by madewild** [comment]
OK for me, I postpone to 1.2 then for the more complex fix. Thanks!

**Comment by D063520** [comment]
We have the code, but it will not make it in this release but in the next one!

**Comment by D063520** [comment]
This is finally fixed. We split the index of the beneficiary. Now it looks like this:

https://kohesio.development.ec.europa.eu/en/beneficiaries?name=university&country=Portugal
