### ISSUE TITLE
Provide region of each project in API

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#11]
Needed to display over the map

**Comment by madewild** [comment]
@D063520 is this finished? or need to postpone to v3?

**Comment by D063520** [comment]
It needs to be postponed, I'm waiting for an answer from thierry

**Comment by madewild** [comment]
@D063520 Thierry seems to be busy with other stuff... can we move forward on this or should we close it for now and concentrate on other priorities? Is this issue likely to come back with other countries?

**Comment by madewild** [comment]
Still not possible to implement? If not I'll close it until it comes back.
