### ISSUE TITLE
Projects near me broken

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#112]
https://kohesio.development.ec.europa.eu/api/facet/eu/map/nearby
https://kohesio.test.ec.europa.eu/api/facet/eu/map/nearby
https://kohesio.acceptance.ec.europa.eu/api/facet/eu/map/nearby

All give 500 errors... to fix asap for Anne's demo!

**Comment by D063520** [comment]
the only problem is that currently I cannot fix anything .... I'm cut out of the infrastructure .....

**Comment by madewild** [comment]
I know Dennis, sorry about this situation... We're looking for a solution with Raph.

**Comment by raphdom** [comment]
this is working:
https://dev.kohesio.linkedopendata.eu/api/facet/eu/map/nearby
@D063520 I've sent you the credentials via teams to access the logs, normally now you can fix on the code and commit and check the logs after the application is restarted(automatically)

**Comment by raphdom** [comment]
It is fixed on test and acceptance.
We have some instability on DEV application now because of the spot instances on AWS side (to be discussed with them)

**Comment by madewild** [comment]
@athollard can you test on ACC?

**Comment by madewild** [comment]
I confirm it works fine on my side...

**Comment by AThollard** [comment]
Fine on my side as well (very slow but that's another issue on my side)
