### ISSUE TITLE
10000000000 cannot be converted to number

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#119]
Starting from https://kohesio.development.ec.europa.eu/projects?sort=Total-Budget-(descending)&totalProjectBudget=1-000-000-000---10-000-000-000:

https://kohesio.development.ec.europa.eu/api/facet/eu/search/project?offset=0&limit=15&budgetSmallerThan=10000000000&budgetBiggerThan=1000000000&orderTotalBudget=false

https://kohesio.development.ec.europa.eu/api/facet/eu/search/project/image?offset=0&limit=15&budgetSmallerThan=10000000000&budgetBiggerThan=1000000000

Both APIs crash with:

There was an unexpected error (type=Bad Request, status=400).
Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "10000000000"

**Comment by D063520** [comment]
probably an overflow

**Comment by madewild** [comment]
@roberto-musmeci do we have so many projects over 1 billion euros? we could simply remove this option in the dropdown filter if easier...

**Comment by roberto-musmeci** [comment]
We have onyl 10 projects above 1bn . I agree with @madewild to remove it

**Comment by D063520** [comment]
no, no, it is easy to fix, we make a long out of an int ....

**Comment by DiaZork** [comment]
It's done

**Comment by madewild** [comment]
@roberto-musmeci we have 8 projects now on https://kohesio.development.ec.europa.eu/projects?sort=Total-Budget-(descending)&totalProjectBudget=1-000-000-000---10-000-000-000 is that correct?

**Comment by roberto-musmeci** [comment]
We have 8 between 1-10bn euros. 
The we have 1 in Hungary of 28 bn euros. It must be wrong. I am checking make sure we address it.
[query](https://query.linkedopendata.eu/#SELECT%20%3Fp%20%3FBdg%0AWHERE%7B%0A%20%20%3Fp%20wdt%3AP35%20wd%3AQ9934%3B%0A%20%20%20%20%20wdt%3AP474%20%20%3FBdg.%0A%20%20FILTER%28%3FBdg%20%3E1000000000%29%0A%20%20%7D%20ORDER%20BY%20DESC%28%3FBdg%29)
