### ISSUE TITLE
First time load problems

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-backend#121]
I noticed that when we restart the backend application the first time that we try to reach some endpoint is loading forever... just need to refresh the page, but it is annoying...

**Comment by D063520** [comment]
Hi Raph, I do not really understand the problem. How can I replicate it? Could it be that it was due to the fact that the endpoint was not started and therefore the backend could not answer?

**Comment by raphdom** [comment]
Hi @D063520. Normally this happen every time that we restart the backend application. You can restart and try to go to the first page of the application. The map will try to load and it will loads forever, but if I refresh the page twice it is working, we could reproduce it only with the backend endpoints also. If you have time we can check together tomorrow...

**Comment by raphdom** [comment]
For me the problem is solved.
