### ISSUE TITLE
Empty project list

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#124]
Happening on edge case but maybe also elsewhere...
https://kohesio.development.ec.europa.eu/beneficiaries/Q3650562

https://kohesio.development.ec.europa.eu/api/facet/eu/beneficiary?id=https://linkedopendata.eu/entity/Q3650562 reports we should expect 45111 projects

but https://kohesio.development.ec.europa.eu/api/facet/eu/beneficiary/project?id=https://linkedopendata.eu/entity/Q3650562&page=0&pageSize=15 has an empty list

**Comment by DiaZork** [comment]
It looks fixed for some reason.... i didn't touch anything maybe it was some cache that wasn't generated yet ?

**Comment by madewild** [comment]
OK strange... let's see if it happens again.
