### ISSUE TITLE
Add PO codes to API

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#127]
Like you did for themes, could you add the PO01, PO02 codes etc. (Policy Objective ID https://linkedopendata.eu/wiki/Property:P1747) in https://kohesio.development.ec.europa.eu/api/facet/eu/policy_objective ? It will allow us to avoid hardcoding on the UI side, thx.

**Comment by madewild** [comment]
Additionnaly, can you sort by PO? (PO1 then PO2 etc.)
Currently the order is strange in the filter (PO1 then PO4...)

**Comment by DiaZork** [comment]
It's good now

**Comment by madewild** [comment]
Thanks, perfect.
Side note: this API is called https://kohesio.development.ec.europa.eu/api/facet/eu/policy_objective (singular) while it should be aligned to https://kohesio.development.ec.europa.eu/api/facet/eu/thematic_objectives (plural).
But let's maybe not change this right now since it will break the UI. ;)
