### ISSUE TITLE
Brittany project list empty on map

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#128]
https://kohesio.test.ec.europa.eu/api/facet/eu/search/project/map?granularityRegion=https://linkedopendata.eu/entity/Q3487 sends back no projects

but on https://kohesio.test.ec.europa.eu/projects?tab=results&country=France&region=Brittany&sort=Total-Budget-(descending) we see 1283 projects

**Comment by madewild** [comment]
(working on https://kohesio.development.ec.europa.eu/api/facet/eu/search/project/map?granularityRegion=https://linkedopendata.eu/entity/Q3487 strange)

**Comment by madewild** [comment]
frozen index issue?

**Comment by D063520** [comment]
No, I fixed this issue silently .... we just have to deploy the new backend .....

**Comment by madewild** [comment]
fyi @roberto-musmeci
