### ISSUE TITLE
Statistical NUTS keep coming back

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#129]
In the beneficiary research page, the filter includes NUTS for Statistical purpose only. 
The effect is that if combined with another filter (e.g. OP), the list of beneficiary is incomplete/incorrect 

![image](https://user-images.githubusercontent.com/86654885/154446845-dd8f979e-bed1-41fe-8b20-b8de54adaa4e.png)

**Comment by madewild** [comment]
Yes they are back again... it's everywhere, also on the map and in projects. We will check why with @D063520

**Comment by D063520** [comment]
wait wait ... it is again this problem that the statistical nuts are not excluded all over the application ..... why!!!!

**Comment by madewild** [comment]
indeed they reappear every day, I think it's an issue with the cache that is computed on the live index instead of the frozen index or something, let's discuss with @raphdom

**Comment by D063520** [comment]
so the pod restarted 6 hours ago .... basically something is going wrong there
kohesio-backend-deployment-0                   2/2     Running     0          6h38m

**Comment by D063520** [comment]
ok, let's discuss at 13:00 ....

**Comment by madewild** [comment]
will be fixed in frozen index
also fix in live index

**Comment by D063520** [comment]
@madewild two things
1) you need to put them as preferred
2) you need to wait one night since the application needs to restart (or you kill the pod and wait)
Since both things will apply tomorrow, please check again .....

**Comment by madewild** [comment]
Perfect in dev this morning.
