### ISSUE TITLE
Projects near me not ordered by distance

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#130]
Projects near me does not alway display Belgium's projects. The only pattern we could find with Pascal is that laptop within VPN network area will display Belgian projects but personnal computers from external zone will not display. Tested with IPAD, Personal desktop, PGA's Unisys laptop and personal IPhone. Cached have been refreshed and when test failed, tried with "private" session.

**Comment by madewild** [comment]
Transferred to backend because it does not look like a frontend issue.
This is the code handling the "nearby" functionality: https://github.com/ec-doris/kohesio-backend/blob/dev/src/main/java/eu/ec/doris/kohesio/controller/MapController.java
@DiaZork can you help us debug this?

**Comment by madewild** [comment]
Might be related to the limit=2000 parameter. If the function finds 2000 in Germany close to the border, it stops looking...

**Comment by Djang0** [comment]
exact same behavior at https://kohesio.test.ec.europa.eu/

**Comment by madewild** [comment]
yes that's "normal" ;) the nearby code is the same in all ENVs...

**Comment by DiaZork** [comment]
I've find out why it was happening, it's because the query is not order by distance but by default so it's le "lower" IRI that come out first so with the 2000 limit it stop before getting any Belgium project

**Comment by madewild** [comment]
Cool, so basically an order by will fix it? :)

**Comment by DiaZork** [comment]
I made the change, you can try... But now it is quite slow, it take around 30 seconds for the query

**Comment by madewild** [comment]
The spread of the projects is better but 30 seconds is clearly not acceptable. Maybe we can display only 200 projects instead of 2000 if this speeds things up? 200 is already a lot to explore manually on the map...

**Comment by DiaZork** [comment]
This doesn't speed up the query.. The slow thing is the `ORDER BY` which is done before the `LIMIT` 
So what i think can help is to add a FILTER that will keep only the project with a distance lower than a certain distance and that should speed up the ORDER BY by a lot i think

**Comment by madewild** [comment]
OK nice I let you check it...
If we can make it work quick enough, the improvement is clear. I tested by switching to 4G instead of wifi and there I have the same issue as @Djang0 and @gachpas:

TEST (old)
![pnm_test](https://user-images.githubusercontent.com/942488/154987529-29ec7260-7697-48e3-8ecb-83d04d7dba49.png)

DEV (new)
![pnm_dev](https://user-images.githubusercontent.com/942488/154987576-81c7968c-fc7d-41b8-b3fb-cd0738a4b04b.png)

**Comment by madewild** [comment]
We could also retrieve the country from the IP address and then filter on this country in the query, but then we miss interreg cross-border projects etc. To test and decide.

**Comment by DiaZork** [comment]
I've added a filter and it's a lot better the query take a bit less than a second.
I've but a limit of 100 km that i can move is it good ?

**Comment by madewild** [comment]
Much better indeed!
@Djang0 and @gachpas can you test on https://kohesio.development.ec.europa.eu/ ?

**Comment by gachpas** [comment]
@madewild , now I have projects around Liège :)

Thx
