### ISSUE TITLE
Add statistics endpoint data to the cache

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-backend#131]
/api/facet/eu/statistics
The only part on the homepage that is not cached.

**Comment by D063520** [comment]
I added this in the cache, can someone check tomorrow morning, early ; )

**Comment by raphdom** [comment]
Don't forget if you want to reflect this on test environment you should merge into test branch. We are using the latest commit to regenerate the cache on test with the frozen index.

**Comment by D063520** [comment]
I would move all the changes from dev to test in one batch once they are approved on dev ....

**Comment by madewild** [comment]
It's just that the cache behaves a bit differently with live vs frozen index... but OK we can check tomorrow in DEV, then merge to TEST, then check again on Thursday in TEST.

**Comment by madewild** [comment]
I just tested https://kohesio.development.ec.europa.eu/api/facet/eu/statistics and was very quick
but I might have been on the dev homepage before :P

**Comment by madewild** [comment]
@raphdom do you have another way to check if it is fine now? so we can close...

**Comment by raphdom** [comment]
We can close it, let's see on test tomorrow
