### ISSUE TITLE
when clicking on a point ranking the featured projects first

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-backend#132]
It's more a backend issue, but is it ok for you?

<img width="1041" alt="Screenshot 2022-02-18 at 08 00 48" src="https://user-images.githubusercontent.com/10883585/154633780-2550bec4-a7e8-4d4d-adb3-0d4284f388aa.png">

**Comment by madewild** [comment]
Sure, I though it was already the case...
@DiaZork can you take car of that?

**Comment by madewild** [comment]
For instance on https://kohesio.test.ec.europa.eu/api/facet/eu/search/project/map/point?coordinate=21.6267661,52.1569732 we would need the 2 projects with "isHighlighted":true" coming first in the list

**Comment by DiaZork** [comment]
It's done
https://kohesio.development.ec.europa.eu/api/facet/eu/search/project/map/point?coordinate=21.6267661,52.1569732
