### ISSUE TITLE
Exact location not provided in project API

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#137]
https://kohesio.test.ec.europa.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q3133959 is giving "regionText":"Spain"
however this project has a precise geolocation in the Wikibase: https://linkedopendata.eu/wiki/Item:Q3133959

**Comment by DiaZork** [comment]
It was a problem with the entity [Community of Madrid](https://linkedopendata.eu/wiki/Item:Q1135) it was missing the NUTS 2 and NUTS 3 as it normally shoud be.
I will check tomorrow with the new index but it should be fix

**Comment by madewild** [comment]
Still not working on https://kohesio.development.ec.europa.eu/projects/Q3133959 with live index but let's wait for the fozen one to check in test...

PS: ah @DiaZork the new statements were not marked as preferred like NUTS1! I just made them preferred on https://linkedopendata.eu/wiki/Item:Q1135

**Comment by DiaZork** [comment]
It's working now

**Comment by madewild** [comment]
Well not really: it says "multiple locations" whereas there is only one on https://linkedopendata.eu/wiki/Item:Q3133959 ;)

**Comment by DiaZork** [comment]
Right, there is several time the same geoJson ...

**Comment by DiaZork** [comment]
This time it should be good
