### ISSUE TITLE
Empty geoJson

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#138]
https://kohesio.test.ec.europa.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q2548069

geoJson is empty while the (complex) info is available on https://linkedopendata.eu/wiki/Item:Q2548069

**Comment by DiaZork** [comment]
It's fixed
https://kohesio.development.ec.europa.eu/projects/Q2548069
https://kohesio.development.ec.europa.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q2548069

**Comment by madewild** [comment]
Nice!
fyi @roberto-musmeci
