### ISSUE TITLE
Search timing out with budget

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#139]
https://kohesio.test.ec.europa.eu/projects?tab=results&sort=Total-Budget-(descending)&totalProjectBudget=100-000-000---1-000-000-000

runs forever until a timeout

**Comment by DiaZork** [comment]
This is working now so it might be that the cache take too long to generate ?

**Comment by madewild** [comment]
Probably someone tried it today and now it's cached
On https://kohesio.development.ec.europa.eu/projects?tab=results&sort=Total-Budget-(descending)&totalProjectBudget=100-000-000---1-000-000-000 still timing out

**Comment by madewild** [comment]
@DiaZork you can test tomorrow when the cache is clean
you could also switch to other amounts, @roberto-musmeci reported issues with all ranges
kind of linked to #143 but here the filter is part of the problem

**Comment by D063520** [comment]
I added a cache on the budget ranges

**Comment by madewild** [comment]
Perfect for me now!
@roberto-musmeci can you test in dev?

**Comment by roberto-musmeci** [comment]
Searching by ranging of total budgets works perfectly. Thanks a lot 
There is still some problems regarding the ranges of EU contributions. Can we cache also that ?

**Comment by madewild** [comment]
Indeed good idea @roberto-musmeci ! @D063520 can you handle this?

**Comment by D063520** [comment]
I did not even remember that there is this search filter! Added ......

**Comment by madewild** [comment]
Cool, will test tomorrow and close then.

**Comment by madewild** [comment]
Working now.

**Comment by madewild** [comment]
Mmmh https://kohesio.acceptance.ec.europa.eu/projects?amountEUSupport=1-000-000-000---10-000-000-000&sort=Total-Budget-(descending) is also cached? First time I went there I got a timeout:
![eu_cache](https://user-images.githubusercontent.com/942488/155483826-e2937c92-bd8c-4c6b-9e57-bc512577b957.png)

Now it's cached and working.

**Comment by D063520** [comment]
I forgot a to cache the last entry. It has 10 zeros and I put only 9 .....
