### ISSUE TITLE
Missing red circle

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#142]
![missing red circle](https://user-images.githubusercontent.com/942488/154948562-01ee6cc8-564f-4dd0-87d1-1926247401fd.png)

We see this location has a highlighted project but the circle is not red.
We should have at least one "isHighlighted: true" in https://kohesio.development.ec.europa.eu/api/facet/eu/search/project/map?granularityRegion=https://linkedopendata.eu/entity/Q2530082

**Comment by madewild** [comment]
{"isHighlighted":false,"coordinates":"18.628218475573,54.36143405"}

should be

{"isHighlighted":true,"coordinates":"18.628218475573,54.36143405"}

compare with https://kohesio.development.ec.europa.eu/api/facet/eu/search/project/map/point?coordinate=18.628218475573,54.36143405

**Comment by DiaZork** [comment]
It's fixed

**Comment by madewild** [comment]
@roberto-musmeci fyi the Gdansk highlighted projects are finally there on dev :)

![gdansk](https://user-images.githubusercontent.com/942488/155134219-0753d2bf-8feb-4068-a188-685d6d2bab7f.png)
