### ISSUE TITLE
Search performance and persistence

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#143]
Opening up a separate issue to follow up on https://github.com/ec-doris/kohesio.eu/issues/242

https://kohesio.development.ec.europa.eu/search?keywords=job took 17 seconds to load for instance (now it's cached of course)
trying to understand why since it's paginated...is it getting the total which is taking a lot of time?
might be linked to #109 
in pure Lucene we don't have this problem, the total is always available
but with the spraql layer I don't know...

**Comment by madewild** [comment]
Other related issue: if you go to https://kohesio.test.ec.europa.eu/search?keywords=wifi and then refresh several times the page, the results displayed are always different. We should use some kind of sorting/ranking to persist the order even if minimal to avoid further affecting performance.

**Comment by D063520** [comment]
I would remove the count ... the count provided in such search scenarios is never accurate, that is why it is generally fast. Is this fine?

**Comment by madewild** [comment]
But then what do we put in the pagination?

**Comment by D063520** [comment]
We can make it a la amazon and put always 7 pages:

<img width="1074" alt="Screenshot 2022-02-22 at 22 38 32" src="https://user-images.githubusercontent.com/10883585/155224002-9a6f1a0b-8248-4ad5-84e7-361be583d12b.png">

If there are not so many results we will say no result found

**Comment by D063520** [comment]
can you test now on test?

**Comment by madewild** [comment]
I don't see much of a difference...

- https://kohesio.test.ec.europa.eu/search?keywords=car took 9 seconds (4 264 results)
- still different order every time I reload

What did you change?

**Comment by DiaZork** [comment]
We optimize the query, it's better now

**Comment by madewild** [comment]
Much faster indeed and with persistent results on DEV!
I tested with https://kohesio.development.ec.europa.eu/search?keywords=my etc.
Great, closing then.
