### ISSUE TITLE
Non-Kohesio beneficiary in TEST index

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio-backend#147]
https://kohesio.test.ec.europa.eu/beneficiaries/Q2542200

**Comment by D063520** [comment]
I checked a "non-kohesio beneficary" as a subclass of a "beneficary". So it was also a beneficary ... I removed it now. The dumping started some hours ago ... let's see if the data will make it into the next frozen index

**Comment by madewild** [comment]
Still visible on https://kohesio.test.ec.europa.eu/beneficiaries/Q2542200 ...
So will be for next dump/index?

**Comment by D063520** [comment]
Wait .... so it will be there I guess but it will not be findable via the search .... does this make sense?

**Comment by madewild** [comment]
Mmmh not really... for me the correct behaviour is like https://kohesio.development.ec.europa.eu/beneficiaries/Q2542200 which redirects to 404

**Comment by D063520** [comment]
I checked the code ... you are right .... and yes it is because we change it to late .... should I recompute the index again?

**Comment by madewild** [comment]
Not now, maybe next week when we are extra sure that the data is perfect for the release. :)

**Comment by madewild** [comment]
Fixed in TEST today.
