### ISSUE TITLE
Abstract shown on projects search is truncated

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#15]
When searching for keywords, Lucene highlights them and we see only the relevant part but we should at least see the beginning with ...

**Comment by D063520** [comment]
Sorry Max I do not understand anymore the problem here, do you remember?

**Comment by madewild** [comment]
It is the same thing Thierry mentioned, the sentence is cut in the middle. We should add "..." add the end (what Thierry calls "cosmetic change") but maybe we can do it at the UI level? Not sure, to discuss with Raph

**Comment by D063520** [comment]
Now it looks like this:

https://dev.kohesio.eu/projects?keywords=low%20carbon&country=Czech-Republic
