### ISSUE TITLE
cache missing for regions

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-backend#151]
- select italy
- select any region

<img width="1680" alt="Screenshot 2022-02-24 at 09 26 44" src="https://user-images.githubusercontent.com/10883585/155486746-ad81f0f6-3239-4cea-bb3a-b8d8b8c8c037.png">

also on the map .... this is particularly starnge since when we click on the map it is fast. Why are these requests different?

**Comment by D063520** [comment]
ok, it was simply not in the cache .... did not remember this .... now it is ....

**Comment by madewild** [comment]
cool, but this cache has been growing a lot these days... yesterday took 4 hours to generate it! need to monitor that closely

**Comment by D063520** [comment]
oh really! we can also not cache it .... it was not that slow .... I was just surprised that it was not there ....

**Comment by madewild** [comment]
Don't worry, leave it there for now, will open another issue.
