### ISSUE TITLE
Monitor growing cache

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#152]
Cache has been growing a lot these days... yesterday took 4 hours to generate it! need to monitor that closely

_Originally posted by @madewild in https://github.com/ec-doris/kohesio-backend/issues/151#issuecomment-1049728214_

**Comment by D063520** [comment]
On option is to parallelise it probably .....

**Comment by raphdom** [comment]
is more about to generate the cache, if you parallelise on the java side would be great, because we have 2 replicas of the qanswer app to respond of the backend demand, and if need more when we regenerate the cache we can increase only in that moment.

**Comment by D063520** [comment]
what is the current status of this? Is 4 hours too much?

**Comment by raphdom** [comment]
for me it is good, but when we import new projects, maybe it will grow, but we can close it for now... on my opinion
