### ISSUE TITLE
Empty graph viz for beneficiary without EN label

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#156]
For instance:

https://kohesio.development.ec.europa.eu/beneficiaries/Q3831611

click on "Graph" button

https://query.linkedopendata.eu/embed.html#%23defaultView%3AGraph%0ASELECT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20VALUES%20%3Fitem%20%7B%20%3Chttps://linkedopendata.eu/entity/Q3831611%3E%7D%20%3Fitem%20%3FpDirect%20%3FlinkTo%20.%0A%20%20%3Fitem%20rdfs%3Alabel%20%3FitemLabel%20.%0A%20%20FILTER(lang(%3FitemLabel)%3D%22en%22)%0A%7D

Not really a bug but could be improved, disturbing for the user...

**Comment by madewild** [comment]
Proposed fix in dev: https://kohesio.development.ec.europa.eu/beneficiaries/Q3831611

Graph button : https://query.linkedopendata.eu/embed.html#%23defaultView%3AGraph%0ASELECT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20VALUES%20%3Fitem%20%7B%20%3Chttps://linkedopendata.eu/entity/Q3831611%3E%7D%20%3Fitem%20%3FpDirect%20%3FlinkTo%20.%0A%20%20OPTIONAL%7B%3Fitem%20rdfs%3Alabel%20%3FitemLabel%20.%0A%20%20FILTER(lang(%3FitemLabel)%3D%22en%22)%7D%0A%7D

I added an optional clause for the EN label. So it defaults to the URI if no label... Tested live at Cohesion Forum on the big screen with Georgina yesterday :)

**Comment by madewild** [comment]
@D063520 let me know what you think, if good enough we can close...

**Comment by D063520** [comment]
yes, for me it is fine!
