### ISSUE TITLE
Experiment with sense2vec

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#157]
Yesterday during the demo to the board of directors, an interesting point came up: how to differentiate between projects about building real "bridges" vs all the metaphorical "bridges" between people etc.?
In therory sense2vec (https://github.com/explosion/sense2vec) or similar vectors could handle that... to investigate.

**Comment by D063520** [comment]
One approach is to do entity linking over all projects. Then  we would have concepts instead of words. Not sure about the quality though ...
