### ISSUE TITLE
Region alignment

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#16]
Map uses NUTS 2016 whereas the filters use other regions...

**Comment by madewild** [comment]
Postponed to v3 (REGIO decision)

**Comment by D063520** [comment]
Max for this .... I have a solution that does not require DG Regio ... it is related to this https://github.com/ec-doris/kohesio-backend/issues/62. Basically in the list they want this table:
![](https://user-images.githubusercontent.com/10883585/120382466-f664b980-c323-11eb-8479-8859cf69ab87.png)
Or better the first nuts that are attached to the country that are meaningful for the country. I already modeled for the other issue that data so I can create an API that serves this list of regions .... is this fine for you?

**Comment by madewild** [comment]
I think there are several things to consider here:
- the regions in the map are in English (e.g. Piedmont) whereas in the filters they are in local language (e.g. Piemonte)
- sometimes this makes it tricky to find the correspondence: "South Tyrol" on the map vs "Provincia Autonoma di Bolzano/Bozen" in the filters
- when drilling down on "South Italy" on the map, several subregions are missing (Campania, Lazio...) but they are in the filters
- ...

**Comment by D063520** [comment]
Yes, with this strategy
- the names in the map and the names in the drop down will be the same
- I know there is some empty places on the map, it's a bug, I'm trying to fix it
I think it should address everything. I will wait until raph is active again, because we need to port the change also in the front-end....

**Comment by madewild** [comment]
great, go ahead then!

**Comment by D063520** [comment]
I addressed this issue. Can you check if it is fine Max? If you want we can chat, it is easier to explain by voice what I did ....
