### ISSUE TITLE
Add Kohesio examples in Wikibase query endpoint 

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#161]
Some user suggested it would be good to have some Kohesio-related queries in the example list in the SPARQL endpoint. 
Possibly good also for us for very recurrent queries. 
Do we have control over that ? is it feasible and useful in your opinion ? 

![image](https://user-images.githubusercontent.com/86654885/162702064-37c0b741-abfa-4254-a7c8-d54f13d9d1a8.png)

**Comment by madewild** [comment]
Linked to https://github.com/ec-doris/EuKnowledgeGraph/issues/61 and https://github.com/ec-doris/EuKnowledgeGraph/issues/65

**Comment by madewild** [comment]
@D063520 can you report upstream to WMDE?

**Comment by madewild** [comment]
Now available on https://query.linkedopendata.eu/
