### ISSUE TITLE
Encoding issue in beneficiary data dump

### ISSUE THREAD

**Issue by faustusdotbe** [ec-doris/kohesio-backend#162]
Hi,

The new dump at https://kohesio.ec.europa.eu/data/beneficiaries/ displays encoding issues, see eg for `latest_FR.csv`: 

![Screenshot from 2022-05-03 13-59-19](https://user-images.githubusercontent.com/5579081/166449180-d48b7a9c-454c-47b7-b667-aa807854074d.png)

The `.xlsx` files seem to have the same issue.

**Comment by madewild** [comment]
Maybe @svili you can help with this?

**Comment by D063520** [comment]
Was it appearing also in the old dumps?

**Comment by faustusdotbe** [comment]
No, this is new

**Comment by D063520** [comment]
The yes, I think @svili is the best to help out here ....

**Comment by svili** [comment]
For future reference: `requests` assumes non utf-8 encoding for text contents.
Fixed now. We have also rescheduled the cronjob for the data generation so tonight we will create new exports that should not have this issue.
Btw here is the repo for the exporting script: https://github.com/ec-doris/kohesio-exporter

**Comment by svili** [comment]
The new exports are in https://kohesio.test.ec.europa.eu/data/beneficiaries/
But with Roberto we've seen some really weird issue. If we opened https://kohesio.test.ec.europa.eu/data/beneficiaries/latest_BG.csv it looked like it had an encoding error. But not 05-12_BG which are a copy of it. Even weirder is that now the error is gone and it looks fine.
Can you guys check if the files are normal on your end?

**Comment by faustusdotbe** [comment]
Aside from some lines with repeated double quotes (see below), the BG one renders correctly (well, it looks Cyrillic and I havent seen any encoding issues) both in Python and LibreOffice

```
"""МЕГАДОМ""ООД"
"""Евроквалификационен център"" АД (ЕКЦ АД)"
"""Руника ЕМ"" ЕООД"
```

`latest_FR.csv` seems fixed (green rectangles in image below) but shed light on a data issue (red rectangle) that we can actually find in the KB : https://linkedopendata.eu/wiki/Item:Q3764224

![Screenshot from 2022-05-12 10-09-32](https://user-images.githubusercontent.com/5579081/168023827-c30e0cad-8149-45d2-97a6-5053ba6a3ca5.png)

**Comment by faustusdotbe** [comment]
Reopening this issue: shouldn't we be moving the data from https://kohesio.**test**.ec.europa.eu/data/beneficiaries/ to https://kohesio.ec.europa.eu/data/beneficiaries/ ?

**Comment by madewild** [comment]
Yes with the June release ;)
