### ISSUE TITLE
Add managing authority to CSV/XLSX exports

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#165]
Currently this info is not provided...

**Comment by madewild** [comment]
check with @D063520 for the sparql query

**Comment by svili** [comment]
@D063520 Here's the current query: https://github.com/ec-doris/kohesio-exporter/blob/main/queries/projects.sparql
Can you give me here the new line to the select? Or you can edit this also. The strings starting with `PARAM_` are strings I'm replacing for each country in python.
Also if you have a better way of handling parameters to sparql queries please advise.

**Comment by D063520** [comment]
basically we need in the SELECT a:

(GROUP_CONCAT(DISTINCT ?managingAuthorityLabel; SEPARATOR = "|") AS ? ManagingAuthority) 

and in the WHERE here:

https://github.com/ec-doris/kohesio-exporter/blob/9aa18f6b99403044daaadb3acbed3e21e1e60253/queries/projects.sparql#L96

another optional like:

OPTIONAL {
      ?program <https://linkedopendata.eu/prop/direct/P1586> ?managingAuthority .
      OPTIONAL {?managingAuthority rdfs:label ?managingAuthorityLabel.
      FILTER((LANG(?managingAuthorityLabel)) = "en")}
    }
  }

**Comment by madewild** [comment]
Let's postpone this

**Comment by madewild** [comment]
@svili let's fix this together

**Comment by madewild** [comment]
Actually I added this in https://github.com/ec-doris/kohesio-exporter/commit/87fb5f12eb4d16009847d34065fec6f85910116a
Goldfish memory anyone? :D
