### ISSUE TITLE
Allow multiple programmes and budgets for one project

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#166]
Change values to lists in project API
Caution, the order will be important since we need to correlate the programme with the budget!

**Comment by D063520** [comment]
@roberto-musmeci: we would prefer to discuss with you

**Comment by DiaZork** [comment]
Some example for this issues:

https://linkedopendata.eu/wiki/Item:Q3884990
https://linkedopendata.eu/wiki/Item:Q3884860

**Comment by D063520** [comment]
I would put the budget per program as a reefied statement on the program. Like:

projects -> program -> programX
           budgets -> budgetProgramX

like this we have the information, if we want we can render it. The only problem is that if we aggregate the budget by program we will take the whole budget of the project for bot programs. @roberto-musmeci: is this a problem?

**Comment by roberto-musmeci** [comment]
@D063520  I think it's fine to
1) display the aggregate budget across the programs 
2) mention the list of programs in the relevant field

**Comment by madewild** [comment]
Let's add the programmes first and postpone the budget aggregation issue

**Comment by madewild** [comment]
@raphdom to adapt in the frontend
@madewild to check in the exports, pipe separated values?

**Comment by madewild** [comment]
Already the case in export:

```sparql
    (GROUP_CONCAT(DISTINCT ?programLabel; SEPARATOR = "|") AS ?Programme_Name)
```

**Comment by DiaZork** [comment]
It's done in the backend.
You have now a list *program* that contain the list of the program with 3 attributes which are the same as previously: 
- programInfoRegioUrl
- programFullLabel
- programLabel

If you want to [try](https://kohesio.development.ec.europa.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q3884990)

**Comment by raphdom** [comment]
There is no programmingPeriodLabel anymore? Or this is per programme? Can you add this?
What is the max number of programmes that one project can have?

**Comment by roberto-musmeci** [comment]
There is not a maximum of programs but resonably I do not expect more than
4 programs.

**Comment by DiaZork** [comment]
> There is no programmingPeriodLabel anymore? Or this is per programme? Can you add this? What is the max number of programmes that one project can have?

I've added it, it was hard coded so i've done the same

**Comment by raphdom** [comment]
I have put in another box, tell me if you have another suggestion:
<img width="369" alt="Screenshot 2022-09-22 at 08 55 34" src="https://user-images.githubusercontent.com/5124917/191679151-419c61fd-2f46-4ad9-a15b-5b0d1bb2c584.png">

**Comment by madewild** [comment]
@roberto-musmeci what do you think?

**Comment by roberto-musmeci** [comment]
I think you solution is good @raphdom. We can close this.
