### ISSUE TITLE
Thematic objective not displayed

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#169]
for this [project](https://linkedopendata.eu/wiki/Item:Q4294389), the Thematic Objective is in the graph but the icon is not displayed in [Kohesio](https://kohesio.development.ec.europa.eu/en/projects/Q4294389
). 

Is it because the theme is deducted from the intervention field ? In principle, if we have Thematic Objetive information in the graph we should display that. Can we make this change ?

**Comment by madewild** [comment]
@DiaZork can you check why themeLabels and themeIds are empty on https://kohesio.development.ec.europa.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q4294389 ?

Maybe related to https://github.com/ec-doris/kohesio-frontend/issues/650

**Comment by roberto-musmeci** [comment]
@DiaZork Possibly still some problem here

Thematic objective for all projects [here](https://kohesio.test.ec.europa.eu/en/projects?country=Finland&program=2014TC16RFIR001---Interreg-Europe_1&sort=Total-Budget-(descending)) is not displayed in the list of results but it's displayed in the project [fiche](https://kohesio.test.ec.europa.eu/en/projects/Q4297435)
