### ISSUE TITLE
Only one country sent back on project detail page

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#175]
Project https://linkedopendata.eu/wiki/Item:Q4297342 is in Romania and Ukraine.

But on https://kohesio.test.ec.europa.eu/en/projects/Q4297342 it says "multiple locations, Ukraine". Romania is not mentioned although only Romania is in orange on the map:
![romania](https://user-images.githubusercontent.com/942488/174965484-146bf46e-7bd1-4014-ae12-77653050201e.png)

Additionally I removed the "in" (to avoid translation problems in the future) so could you change to "Multiple locations, Romania-Ukraine"?

**Comment by DiaZork** [comment]
It's done in the backend, but it will need some change in the frontend, the following fields were string and are now array
- countryLabel
- countryCode

**Comment by D063520** [comment]
Are you sending also 2 geometries?

**Comment by DiaZork** [comment]
This was already working but sometime for country outside EU it doesn't have the geometry so it doesn't display it

**Comment by raphdom** [comment]
now, it is working on dev properly, tell me when do you want to send it to TEST @DiaZork
