### ISSUE TITLE
Filter for interreg projects

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#179]
Find a way to select all interreg projects without going country by country

**Comment by DiaZork** [comment]
It's added too,
In **/api/facet/eu/search/project** we now have a **interreg** parameter with 3 cases :
- null (not set) : whatever project
- false : exclude interreg projects
- true : only interreg projects

**Comment by madewild** [comment]
Great, so @raphdom you can take it from here?

**Comment by D063520** [comment]
Hope this will scale, especially the "false value" is heavy ....

**Comment by madewild** [comment]
Follow-up on https://github.com/ec-doris/kohesio-frontend/issues/669
