### ISSUE TITLE
Export slowness

### ISSUE THREAD

**Issue by svili** [ec-doris/kohesio-backend#183]
Exporting takes around 15 hours every day.
[generate-exports-2022-09-25.log](https://github.com/ec-doris/kohesio-backend/files/9644338/generate-exports-2022-09-25.log)

The export generation script can be found here: https://github.com/ec-doris/kohesio-exporter

**Comment by madewild** [comment]
@svili @D063520 any improvement on this?

**Comment by D063520** [comment]
No, I had no time to check it, I would put it in the things to check for the next release. It is also not super strange. Exporting Wikidata takes 7 days with 17 billion triples. We are at nearly 1 billion now ....

**Comment by madewild** [comment]
@svili is this still a blocking point or can we close?
