### ISSUE TITLE
Greek programs not appearing in Program filters 

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#184]
If you select Greece in the country filters, only INTERREG programs are shown in the Programme Filter. 
I suppose it's due to the EL-GR discrepancies in the country labels. 
Is there a quick fix we can deploy ? 

https://kohesio.ec.europa.eu/en/projects?page=2&country=Greece&sort=Total-Budget-(descending)

**Comment by DiaZork** [comment]
Look like the greek program are missing P32 
https://linkedopendata.eu/wiki/Item:Q2463300

**Comment by madewild** [comment]
Added! :)

**Comment by madewild** [comment]
Ah there are several... let's add them everywhere then

**Comment by DiaZork** [comment]
I can do it 
i have a small script to do it

**Comment by madewild** [comment]
As you wish, I already fixed half manually ;)

**Comment by DiaZork** [comment]
It's done !

**Comment by madewild** [comment]
So we wait until tomorrow for this to be reindexed in test, and then move to ACC ?

**Comment by madewild** [comment]
fyi @raphdom @svili
