### ISSUE TITLE
Allow QID parameter in all filters queries

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-backend#186]
Be able to query all filters with QID, in order to translate the URL when user switch between languages.

**Comment by DiaZork** [comment]
For each method of the facet controller i added a qid parameter **qid** with qid the entity you want to query.
So it's  like the following
https://kohesio.development.ec.europa.eu/api/facet/eu/countries?qid=https://linkedopendata.eu/entity/Q8&language=en
