### ISSUE TITLE
Porto NUTS 3 not accessible from the map 

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#187]
In the main page, users cannot reach Porto NUTS 3 region. 
If you click on the Norte Region (NUTS 2), Porto does not appear among the clickable NUTS 3 regions. However, it should be there.  

The filters for NUTS 3 region in the project research page instead works just fine.

**Comment by D063520** [comment]
@roberto-musmeci can you check again? in Dev or TEST?

**Comment by roberto-musmeci** [comment]
it works thanks :)
