### ISSUE TITLE
English labels in map API

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-backend#191]
Example: https://kohesio.development.ec.europa.eu/api/facet/eu/search/project/map?granularityRegion=https://linkedopendata.eu/entity/Q18&language=el

Still have some english labels, even if I specify the language

**Comment by DiaZork** [comment]
It's fixed. 
For the NUTS there is a hashmap that was initialised only the first time we use it so only with the first language used. That's why only english was available
