### ISSUE TITLE
Improve semantic models

### ISSUE THREAD

**Issue by faustusdotbe** [ec-doris/kohesio-backend#194]
Somehow some things went through the regex, such as parentheses (see picture).

![image](https://user-images.githubusercontent.com/5579081/204500307-1c4071e8-e71e-40ed-a7cf-7b441ca317c1.png)

Do more quality eval and update model.

NB: models aren't made nor deployed in this repo, but I put the issue here for the sake of visibility as I don't know what kohesio-but-not-DORIS colleagues have access to.

**Comment by D063520** [comment]
ok!

**Comment by faustusdotbe** [comment]
Similarity endpoints now serve cleaner models

**Comment by madewild** [comment]
Another so-so example in French: https://kohesio.ec.europa.eu/fr/projets?mots-cl%C3%A9s=nature&trier=Budget-total-(ordre-d%C3%A9croissant)

**Comment by madewild** [comment]
@faustusdotbe do it make sense to keep this open indefinitely? or can we say the current ones are good enough, and open custom issues if something specific pops up?

**Comment by faustusdotbe** [comment]
I like open issues as they remind me there's still work to do, but I understand this might not fit in a larger project. 

There are a few low-hanging fruits I would like to fix that don't take much time. How about we keep this open for one month and I put myself a reminder to close the issue then?

**Comment by madewild** [comment]
Perfect, let's keep it for the December release and then close

**Comment by faustusdotbe** [comment]
As agreed I'm closing this. Models should be better and will be deployed once I unbreak the drive-in.
