### ISSUE TITLE
Improve interaction between filters

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#195]
For instance, NUTS3 should be pre-filtered if country is selected.
Other interactions (programmes etc.) to be defined.

**Comment by DiaZork** [comment]
It's done. @raphdom 
So for the program facet we have 2 new parameters
- **region** that is a NUTS and will give all the program that apply to this NUTS (so if it's a NUTS2 you will also have the program that apply to the NUTS1 in which this NUTS2 is contained.
- **interreg** that is a boolean. It has the same behavior that on projects. If not set will give you every type of program, if **true** only interreg programs if false every program that is not a interreg program

**Comment by roberto-musmeci** [comment]
@DiaZork @raphdom 

Maybe there is something wrong. 
If you select Austria, then Carinthia [here](https://kohesio.development.ec.europa.eu/en/projects?country=Austria&region=Carinthia&sort=Total-Budget-(descending)), you cannot chose any Program for the Program Type "investment Jobs and Growth"

Instead we should be able to select at least [this program](https://linkedopendata.eu/wiki/Item:Q2463050)

**Comment by raphdom** [comment]
This is empty:

https://kohesio.development.ec.europa.eu/api/facet/eu/programs?country=https://linkedopendata.eu/entity/Q16&region=https://linkedopendata.eu/entity/Q2636&interreg=false&language=en

**Comment by madewild** [comment]
If we remove the region it works: https://kohesio.development.ec.europa.eu/api/facet/eu/programs?country=https://linkedopendata.eu/entity/Q16&interreg=false&language=en

So I guess Carinthia is not specific to this programme... it's implicit that a national programme encompasses all regions of the country, @DiaZork can you handle that?

**Comment by DiaZork** [comment]
Okay I look into it but that's strange it should already take care of this kind of case

**Comment by DiaZork** [comment]
Should be fix now.
