### ISSUE TITLE
Missing outermost region

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#196]
https://kohesio.test.ec.europa.eu/fr/

![lareunion](https://user-images.githubusercontent.com/942488/206203322-305dd54c-58da-4ed4-aaf3-2ffb14058ff8.png)

The label "La Réunion" is not under the corresponding polygon.

**Comment by DiaZork** [comment]
The problem is that this entity [Q2576740](https://linkedopendata.eu/entity/Q2576740) is only in english and is missing other labels.

**Comment by madewild** [comment]
OK. Should we mark https://linkedopendata.eu/wiki/Item:Q197 instead as the NUTS3 region? Or copy over the labels to  Q2576740?

**Comment by madewild** [comment]
Yes, the second one has only a few labels... So should we mark Q197 as the NUTS and remove the other one, or copy over the labels?
@D063520 @roberto-musmeci any preference?

**Comment by DiaZork** [comment]
I've put a fallback on the english label in the backend for the moment.
