### ISSUE TITLE
list of operation metadata

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#208]
we would like to show metadata about the list of the operation in the Kohesio FAQ page. 
I imported the data in the KG. see SPARQL [query](https://query.linkedopendata.eu/#SELECT%20%3Flist_of_operation_label%20%3Flist_of_operation_id%20%3Flist_of_operation_qid%20%3Flist_of_operation_url%20%3Flist_of_operation_first_ingestion%20%3Flist_of_operation_last_update%20%28group_concat%28distinct%20%3Fcci%3Bseparator%3D%22%2C%20%22%29%20as%20%3Flist_of_operation_associated_ccis%29%0A%0AWHERE%7B%0A%20%20%3Flist_of_operation_qid%20wdt%3AP35%20wd%3AQ4552790%3B%0A%20%20%20%20%20%20%20%20%20%20%20wdt%3AP578950%20%3Flist_of_operation_id%3B%0A%20%20%20%20%20%20%20%20%20%20%20rdfs%3Alabel%20%3Flist_of_operation_label%3B%0A%20%20%20%20%20%20%20%20%20%20%20wdt%3AP578951%20%3Flist_of_operation_url%3B%0A%20%20%20%20%20%20%20%20%20%20%20wdt%3AP579181%20%3Fprg.%0A%20%20FILTER%28lang%28%3Flist_of_operation_label%29%3D%27en%27%29%0A%0A%20%20%3Fprg%20wdt%3AP1367%20%3Fcci%0A%20%20OPTIONAL%7B%3Flist_of_operation_qid%20wdt%3AP579182%20%3Flist_of_operation_first_ingestion%7D%0A%20%20OPTIONAL%7B%3Flist_of_operation_qid%20wdt%3AP579183%20%3Flist_of_operation_last_update%7D%0A%20%20%0A%7D%20GROUP%20BY%20%3Flist_of_operation_label%20%3Flist_of_operation_id%20%3Flist_of_operation_qid%20%3Flist_of_operation_url%20%3Flist_of_operation_first_ingestion%20%3Flist_of_operation_last_update).

@DiaZork, Can we adapt the backend ?

**Comment by D063520** [comment]
We discussed this morning, Jonathan will take care ...

**Comment by DiaZork** [comment]
It's done!
So you can find at https://kohesio.development.ec.europa.eu/api/facet/eu/loo_metadata the data from the query you shared.
So for each LoO we have:
- **instance** the URI
- **instanceLabel** the label in the language ask in the query with a fallback in english if the language is missing.
- **id** the id of the LoO
- **url** the url of the LoO
- **first_ingestion** the date of the first ingestion
- **last_update** the date of the last update (can be null)
- **ccis** a list of the CCIs in that is contain in the LoO

**Comment by roberto-musmeci** [comment]
@raphdom can we have a first attempt for a table following the schema below ? 
Since the table could be long, we can put it at the end of the FAQ page

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/musmero/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/musmero/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



List of operation   id | List   of operation title | List   of operation URL | Date   of last update in Kohesio | CCIs   covered by the list of operations

-- | -- | -- | -- | --
id | instanceLabel | url | last_update | ccis



</body>

</html>

**Comment by roberto-musmeci** [comment]
@DiaZork  I spoke to @raphdom about this. Since the table would be very long, we were thinking about a filtering funciton by country. This would require to adapt the API to include the country. Is this modification feasible ? 

I will add a statement P32 (country) to each list of operation item today.

**Comment by raphdom** [comment]
It will be something like this?
https://kohesio.development.ec.europa.eu/api/facet/eu/loo_metadata?country=https://linkedopendata.eu/entity/Q18

**Comment by DiaZork** [comment]
Yes but that's strange that it's failing for Portugal… But not for [France](https://kohesio.development.ec.europa.eu/api/facet/eu/loo_metadata?country=https://linkedopendata.eu/entity/Q20). It look like France is more the exception because [Spain](https://kohesio.development.ec.europa.eu/api/facet/eu/loo_metadata?country=https://linkedopendata.eu/entity/Q7) fail to. 
It might be link to the fact that I tried with France this morning and in the meantime the endpoint has gone done? 
I think dev is using https://eu.the-qa-company.com/api/endpoint/commission/eu/sparql also right? and it's down…
