### ISSUE TITLE
Mayotte randomly placed

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#21]
For instance on https://dev.kohesio.eu/projects/Q2494161 refresh several times the page:

In Mayotte, SLOVENIJA, Turkey
In Mayotte, Brandenburg, Romania
In Mayotte, ΚΕΝΤΡΙΚΗ ΕΛΛΑΔΑ, United Kingdom
etc.

**Comment by D063520** [comment]
I think this is a bug in the SPARQL endpoint of wikidata. This is right:

https://query.linkedopendata.eu/#select%20%3Fs0%20%20%3FregionId%20%3Fregion%20%3FregionLabel%20%3FregionUpper1%20%3FregionUpper1Label%20%3FregionUpper2Label%20%3FregionUpper3Label%20where%20%7B%20%0A%20%20VALUES%20%3Fs0%20%7B%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ2494161%3E%20%7D%20%20%0A%20%20%3Fs0%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3Flabel.%20%20FILTER%28%28LANG%28%3Flabel%29%29%20%3D%20%22en%22%29%20%20%0A%20%20OPTIONAL%20%7B%3Fs0%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3Fregion%20.%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%3Fregion%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP192%3E%20%3FregionId%20.%7D%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%3Fregion%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ2576750%3E%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Fregion%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3FregionLabel%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20FILTER%28%28LANG%28%3FregionLabel%29%29%20%3D%20%22en%22%29%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Fregion%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3FregionUpper1%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3FregionUpper1%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ2576674%3E%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3FregionUpper1%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3FregionUpper1Label%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20FILTER%28%28LANG%28%3FregionUpper1Label%29%29%20%3D%20%22en%22%29%20.%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%3FregionUpper1%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3FregionUpper2%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%3FregionUpper2%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ2576630%3E%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3FregionUpper2%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3FregionUpper2Label%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20FILTER%28%28LANG%28%3FregionUpper2Label%29%29%20%3D%20%22en%22%29%20%7D%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%20%3FregionUpper2%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3FregionUpper3%20.%20%20%20%20%20%20%20%20%20%20%20%20%3FregionUpper3%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3FregionUpper3Label%20.%20%20%20%20%20%20%20%20%20%20%20%20%3FregionUpper3%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ510%3E%20.%20%20%20%20%20%20%20%20%20%20%20FILTER%28%28LANG%28%3FregionUpper3Label%29%29%20%3D%20%22en%22%29%20%7D%7D%20%7D%20%0A%7D

while this is not:

https://query.linkedopendata.eu/#select%20%3Fs0%20%20%3FregionId%20%3Fregion%20%3FregionLabel%20%3FregionUpper1%20%3FregionUpper1Label%20%3FregionUpper2Label%20%3FregionUpper3Label%20where%20%7B%20%0A%20%20VALUES%20%3Fs0%20%7B%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ2494161%3E%20%7D%20%20%0A%20%20%3Fs0%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3Flabel.%20%20FILTER%28%28LANG%28%3Flabel%29%29%20%3D%20%22en%22%29%20%20%0A%20%20OPTIONAL%20%7B%3Fs0%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3Fregion%20.%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%3Fregion%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP192%3E%20%3FregionId%20.%7D%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%3Fregion%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ2576750%3E%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Fregion%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3FregionLabel%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20FILTER%28%28LANG%28%3FregionLabel%29%29%20%3D%20%22en%22%29%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%3Fregion%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3FregionUpper1%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3FregionUpper1%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ2576674%3E%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3FregionUpper1%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3FregionUpper1Label%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20FILTER%28%28LANG%28%3FregionUpper1Label%29%29%20%3D%20%22en%22%29%20.%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%3FregionUpper1%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3FregionUpper2%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%3FregionUpper2%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ2576630%3E%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3FregionUpper2%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3FregionUpper2Label%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20FILTER%28%28LANG%28%3FregionUpper2Label%29%29%20%3D%20%22en%22%29%20%7D%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20OPTIONAL%20%7B%20%3FregionUpper2%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3FregionUpper3%20.%20%20%20%20%20%20%20%20%20%20%20%20%3FregionUpper3%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E%20%3FregionUpper3Label%20.%20%20%20%20%20%20%20%20%20%20%20%20%3FregionUpper3%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ510%3E%20.%20%20%20%20%20%20%20%20%20%20%20FILTER%28%28LANG%28%3FregionUpper3Label%29%29%20%3D%20%22en%22%29%20%7D%7D%20%7D%20%0A%7D

**Comment by D063520** [comment]
what an error! it was not a bug in the sparql endpoint .... what happend was that

1) mayotte was aligned to a wikidata entity
2) when the wikidata statements were imported then one of the sattements had preffered rank
3) in consequence mayotte was not anymore a nuts 2 statstical entity..

Is fixed
