### ISSUE TITLE
Issue on the map tab 

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#210]
I noticed that with this filter [combination](https://kohesio.ec.europa.eu/en/projects?keywords=%22Ukraine%22%20AND%20(%22Russian%22%20OR%20%22war%22%20OR%20%22aggression%22)&sort=Total-Budget-(descending)&fund=ESF---European-Social-Fund&country=Poland&tab=map), the map [tab](https://kohesio.ec.europa.eu/en/projects?keywords=%22Ukraine%22%20AND%20(%22Russian%22%20OR%20%22war%22%20OR%20%22aggression%22)&sort=Total-Budget-(descending)&fund=ESF---European-Social-Fund&country=Poland&tab=map) does not work properly.

**Comment by raphdom** [comment]
The API doesn't return the coordinates, can you debug it @D063520 

https://kohesio.ec.europa.eu/api/facet/eu/search/project/map?keywords=%22Ukraine%22%20AND%20(%22Russian%22%20OR%20%22war%22%20OR%20%22aggression%22)&country=https://linkedopendata.eu/entity/Q13&fund=https://linkedopendata.eu/entity/Q2504370&granularityRegion=https://linkedopendata.eu/entity/Q13&language=en

**Comment by madewild** [comment]
Seems to work now...
