### ISSUE TITLE
CCI parameter for the map

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#211]
Could we include a CCI parameter, so to be able to set up the map based only a CCI?

**Comment by DiaZork** [comment]
This is done. So you have now a cci parameter, for example
https://kohesio.development.ec.europa.eu/api/facet/eu/search/project/map?language=en&cci=2014BE05M9OP001

**Comment by roberto-musmeci** [comment]
Feature is implemented. @raphdom  @DiaZork  many thanks
https://kohesio.development.ec.europa.eu/en/map?cci=2014BE05M9OP001

**Comment by D063520** [comment]
Nice! Suggestion: should we not put a little link with Data from Kohesio.eu?
