### ISSUE TITLE
Filter by project types

### ISSUE THREAD

**Issue by DiaZork** [ec-doris/kohesio-backend#220]
Major projects, Regio stars, award winners, best practices

**Comment by D063520** [comment]
@roberto-musmeci followup question on this, we know what a regio star project is, but how can we identify the other categories in the data?

**Comment by roberto-musmeci** [comment]
My idea was to create a 'instance of REGIO STAR' sort of statement. 
So depending on the selected type the query would look like. 
SELECT ?p
WHERE {
?p wdt:P35 wd:[regio star qid/info regio project qid]
}

Does it make sense ?
