### ISSUE TITLE
Select multiple intervention fields

### ISSUE THREAD

**Issue by DiaZork** [ec-doris/kohesio-backend#221]
@roberto-musmeci 
Multiple intervention fields as a OR or AND ?
Like if the request ask for [Q200641](https://linkedopendata.eu/entity/Q200641) and [Q200642](https://linkedopendata.eu/entity/Q200642) should it be the union of the project that have one or the other or should the projects have both of them as intervention field?

**Comment by roberto-musmeci** [comment]
Most projects have only one intervention field attached to them. 
Therefore it should be as OR. We want to retrieve projects that have either [Q200641](https://linkedopendata.eu/entity/Q200641) or [Q200642](https://linkedopendata.eu/entity/Q200642)
