### ISSUE TITLE
Problem with number of results not coherent

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-backend#223]
the second query should return more results, but it does not:

https://kohesio.ec.europa.eu/en/projects?keywords=%22climate%20change%22&sort=Total-Budget-(descending)

https://kohesio.ec.europa.eu/en/projects?keywords=%22climate%20change%22%20OR%20%22elderly%22&country=Austria&sort=Total-Budget-(descending)

**Comment by madewild** [comment]
I checked but you first link is not filtering on Austria so https://kohesio.ec.europa.eu/en/projects?keywords=%22climate%20change%22&sort=Total-Budget-(descending)&country=Austria is more relevant. It gives 57 projects and https://kohesio.ec.europa.eu/en/projects?keywords=%22climate%20change%22%20OR%20%22elderly%22&country=Austria&sort=Total-Budget-(descending) has 74 so for me it looks coherent.
@D063520 can we close?

**Comment by D063520** [comment]
I think yes
