### ISSUE TITLE
repeated projects in beneficiary list

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#226]
A user noted that in some cases the beneficiary fiche contains duplicates in the projects list 
See https://kohesio.ec.europa.eu/en/beneficiaries/Q3213549 and https://kohesio.ec.europa.eu/en/beneficiaries/Q3167823 

Note that the number of projects in the left pane is lower than the number of projects displayed in the list

**Comment by D063520** [comment]
query to retrive duplicates:

PREFIX wdt: <https://linkedopendata.eu/prop/direct/>
SELECT ?s (count(?o) as ?c) WHERE {
  ?s wdt:P835 ?o .
} group by ?s  having (?c>1) order by DESC(?c)

**Comment by D063520** [comment]
It's solved:

https://kohesio.development.ec.europa.eu/en/beneficiaries/Q3213549

https://kohesio.development.ec.europa.eu/en/beneficiaries/Q3167823
