### ISSUE TITLE
Fallback to english if NUTS translations don't exist

### ISSUE THREAD

**Issue by svili** [ec-doris/kohesio-backend#230]
Original frontend bug: https://github.com/ec-doris/kohesio-frontend/issues/859

**Comment by DiaZork** [comment]
It's fixed for dev. A fallback to the english label has been add if the wanted language is not there. It should fix the error.
https://kohesio.development.ec.europa.eu/hu/?t%C3%A9rk%C3%A9pR%C3%A9gi%C3%B3=Magyarorsz%C3%A1g,Budapest,Q2576842#t%C3%A9rs%C3%A9gem

**Comment by D063520** [comment]
I think we want a hot fix in prod for this. @svili can you check if it is fine and deploy it? @DiaZork can you already move to staging?

**Comment by svili** [comment]
Its out on acceptance, can you guys check it?

**Comment by DiaZork** [comment]
It's working fine for me

**Comment by svili** [comment]
Thanks, unfortunately I lost my eu login acceptance password, cause Chrome overwritten it with the normal one when I changed it...
If no error comes back from anyone by tomorrow I'll deploy it to prod.

**Comment by svili** [comment]
Deployed to prod.
