### ISSUE TITLE
Project not indexed in search

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#233]
Project https://kohesio.development.ec.europa.eu/en/projects/Q3697045 is not findable through keyword search not filters. 
https://kohesio.development.ec.europa.eu/en/projects?keywords=pierre%20janet&sort=Total-Budget-(descending) gives no results.
However it is visible in the list of the beneficiary: https://kohesio.development.ec.europa.eu/en/beneficiaries/Q2536134

Indexation problem?

**Comment by D063520** [comment]
Is this problem also in PROD?

**Comment by madewild** [comment]
yes

**Comment by D063520** [comment]
fixed on prod
