### ISSUE TITLE
add Regio Stars candidate to API

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#242]
Can we add projects marked with P35 ->  [Regio Stars 2023 - Candidate](https://linkedopendata.eu/wiki/Item:Q6869909) to the [Project Collection](https://kohesio.ec.europa.eu/en/projects?sort=Total-Budget-(descending)&projectCollection=Regio-Star) filter ? 
[list of projects](https://query.linkedopendata.eu/#SELECT%20%3Fp%20%3Fid%0AWHERE%7B%0A%20%20%3Fp%20wdt%3AP585847%20%3Fid%0A%20%20%20%20%7D)

**Comment by D063520** [comment]
Can you check? should be fine ...

**Comment by madewild** [comment]
Was this projectCollection filter ever deployed?
@roberto-musmeci @Dgojsic what's the status of this?

**Comment by Dgojsic** [comment]
Seems to have been deployed successfully.

**Comment by madewild** [comment]
But not exposed in UI ?

**Comment by madewild** [comment]
Oh yes it is, sorry.
The filter names are:
https://kohesio.ec.europa.eu/en/projects?sort=Total-Budget-(descending)&projectCollection=Regio-Stars-winner
https://kohesio.ec.europa.eu/en/projects?sort=Total-Budget-(descending)&projectCollection=Regio-Stars-2023---Candidate

Closing then.
