### ISSUE TITLE
Duplicates projects in beneficiary fiche info

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#245]
some projects are repeated in the beneficiaries fiches 
[Consejería de Educación](https://kohesio.ec.europa.eu/es/beneficiarios/Q3213251)

both lines point to the same entity in the wikibase 

![image](https://github.com/ec-doris/kohesio-backend/assets/86654885/e4ad29da-662d-4770-b44d-a0b943ec8784)

**Comment by D063520** [comment]
I checked ... this is a data problem:

https://linkedopendata.eu/wiki/Item:Q3213582

there is this entry with 2 budgets .... let you check on your side ....

**Comment by madewild** [comment]
@Dgojsic can you take this over?

**Comment by Dgojsic** [comment]
I removed the incorrect budget line in the wikibase, so this should be addressed if that was the issue.

**Comment by madewild** [comment]
Already fixed on https://kohesio.development.ec.europa.eu/es/beneficiarios/Q3213251 great
