### ISSUE TITLE
Program filter showing some bad results

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-backend#250]
We have a problem with the program filter, showing some bad interreg programs for Belgium, for example:

https://kohesio.development.ec.europa.eu/wikibase/facet/eu/programs?country=https://linkedopendata.eu/entity/Q8

**Comment by DiaZork** [comment]
By default the behavior of this api is that you get all program of a country, interreg included 
Then there is the `interreg` field that 
- if set to true return only interreg program (ie having the statement [P579160](https://linkedopendata.eu/prop/direct/P579160) [Q4554132](https://linkedopendata.eu/entity/Q4554132))
- if set to false return only not interreg program (ie not having the previous statement)

I can change this behavior if needed but you can also just call the API with a false interreg

**Comment by DiaZork** [comment]
Okay so i guess the question is 
Is it normal that Belgium is in [Interreg V-A — Espagne-France-Andorre (POCTEFA)](https://linkedopendata.eu/entity/Q2463550) because it's a data problem in that case…

**Comment by raphdom** [comment]
yeah, maybe it is not a backend problem, feel free to transfer this to another repo, Thanks @DiaZork

**Comment by madewild** [comment]
I removed Belgium from https://linkedopendata.eu/wiki/Item:Q2463550, let's see if it fixes the issue...

**Comment by madewild** [comment]
I also removed Belgium from a few others... Dunno how it got in there.

**Comment by Dgojsic** [comment]
Just seeing this now, in the case Raph mentioned (2014TC16RFCB006 - Interreg V-A - Spain-France-Andorra (POCTEFA), i looked at the source data, and there is indeed 1 beneficiary of 1 project located in Brussels. So the issue was most likely that for interreg projects (at least if they were fed from keep.eu, which doesn't have project locations) the beneficiary location was used instead. Probably also the case in the other instances

**Comment by madewild** [comment]
Ok, but so was I right to remove Belgium from these programmes?

**Comment by madewild** [comment]
@Dgojsic what's the final decision on this?

**Comment by Dgojsic** [comment]
Can be closed, I will create a new issue shortly about our idea from last week to address this more comprehensively (i.e. tinkering with the relevance score)
I have also just noticed i don't have the necessary rights on github to close issues not opened by me, so if you assign it to me, I can close them in the future.

**Comment by madewild** [comment]
I granted you elevated rights for the future
