### ISSUE TITLE
Map API potential bug

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-backend#251]
Is it normal we have different results in this two queries:

https://kohesio.ec.europa.eu/api/map/search?country=https://linkedopendata.eu/entity/Q22&region=https://linkedopendata.eu/entity/Q4397&granularityRegion=https://linkedopendata.eu/entity/Q2502794&language=en

https://kohesio.ec.europa.eu/api/map/search?granularityRegion=https://linkedopendata.eu/entity/Q2502794&language=en

It was Alain that spotted differences between the two maps:

https://kohesio.ec.europa.eu/en/?mapRegion=Germany,Thuringia,Gotha,Q2502794#my-region

https://kohesio.ec.europa.eu/en/projects?country=Germany&region=Thuringia&tab=map&mapRegion=Germany,Thuringia,Gotha,Q2502794#my-region

**Comment by DiaZork** [comment]
So this is the intend behavior i think.
When you only give granularity region you ask for point that are geographically (meaning in the geometry of the nuts link to this granularity region)
in this region but with the country and and region we get the thing that are explicitly link (P32 for country and P1845 for region) so i guess the difference come from that

**Comment by D063520** [comment]
@DiaZork you commented already on this ... can you check again? from what they showed today it seams the behaviour is not as expected ...

**Comment by DiaZork** [comment]
I've fixed it on dev
