### ISSUE TITLE
Filtering for JTF Fund returns empty

### ISSUE THREAD

**Issue by svili** [ec-doris/kohesio-backend#253]
12 new JTF fund projects have been ingested in March, e.g.: https://linkedopendata.eu/wiki/Item:Q7319841
The projects are in Kohesio: https://kohesio.ec.europa.eu/en/projects/Q7319841
Yet the backend returns empty when querying for the fund: https://kohesio.ec.europa.eu/api/projects?offset=0&limit=15&language=en&fund=https%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ7319619

**Comment by D063520** [comment]
hola, one problem is that these projects do not have a readability score .... but I will change the backend to still give back

**Comment by D063520** [comment]
2 is fixed. I noticed another data problem though, there is no budget. I think there I should not make a workaround, it is a data problem:

https://query.linkedopendata.eu/#%20SELECT%20%28COUNT%28DISTINCT%20%3Fs0%29%20as%20%3Fc%20%29%20WHERE%20%7B%20%3Fs0%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ9934%3E%20.%20%3Fs0%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1584%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ7319619%3E%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Fs0%20wdt%3AP474%20%3Fb%7D%20

**Comment by Dgojsic** [comment]
When filtering projects for JTF on both test and production, no projects appear, only on the map view doe the 12 originally ingested projects appear
