### ISSUE TITLE
Operator AND by default?

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#26]
According to Lucene doc, "The OR operator is the default conjunction operator. This means that if there is no Boolean operator between two terms, the OR operator is used." (https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Boolean%20operators)

However, Google used the AND operator by default (https://support.google.com/websearch/answer/2466433?hl=en) so expectations from the users might be different. To discuss before changing (if possible in Lucene).

**Comment by D063520** [comment]
I didn;t new that!

**Comment by madewild** [comment]
Well one learns every day ;)

**Comment by madewild** [comment]
There is a bug with the AND: even if asking for 15 results we get only 5:
![5results](https://user-images.githubusercontent.com/942488/95311067-6d2cde00-088d-11eb-9bbf-239f51b4baaf.png)
And the OR does not work anymore in dev...

**Comment by AlyHdr** [comment]
If the text doesn't contains one of those: "AND" "OR" "NOT" , then all spaces are replaced with AND as a default behavior to do..
