### ISSUE TITLE
make connection with CORDA beneficiaries

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-backend#266]
@madewild @Dgojsic can we agree that we try for the meeting to add into the knwoledge graph at least the links that are sure in the sense we discussed. Like this we have some concrete progress. We could also say we have added in DEV a link when it exists.

**Comment by madewild** [comment]
Sounds good to me!

**Comment by D063520** [comment]
Queries for statistics:

**Comment by Dgojsic** [comment]
many thanks @D063520 . Just to confirm (relating to the ratio), you mentioned there being a 1% overlap somewhere, and this shows much less than that. Was this matched with all 1.9m projects or just a subset, out of which the 1% overlap results? Sorry, just to be clear which metrics I should highlight

**Comment by D063520** [comment]
it is still running ....

**Comment by D063520** [comment]
and there are 700k ben in CORDA. 1% of these overlap, i.e. 7.000

**Comment by Dgojsic** [comment]
Thanks! I confused 1% of our beneficiaries being in CORDA vs CORDA's 1% being in ours. Thanks for clarifying!

**Comment by D063520** [comment]
finished!
