### ISSUE TITLE
Blank Polish beneficiaries

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#28]
A lot of Polish beneficiaries have blank labels. For instance with search https://kohesio.eu/beneficiaries?name=green : 
![pl_blank](https://user-images.githubusercontent.com/942488/93448758-3d189d80-f8d4-11ea-929f-f39c7dfd4f2a.png)

**Comment by D063520** [comment]
The problem was that some polish beneficiares had the label in czech ....
