### ISSUE TITLE
Semantic search

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#30]
Use word2vec (or similar) to allow smarter search across all fields

**Comment by madewild** [comment]
Very interesting approach : http://kbresearch.nl/xportal/#demo

**Comment by madewild** [comment]
@devironl not urgent at all but I might need your help at some point

**Comment by madewild** [comment]
@AlyHdr we have some strange results
https://dev.kohesio.eu/projects?keywords=ai
the first results are OK but at the bottom of the page, nothing matches ai or extended keywords...

**Comment by madewild** [comment]
Even with quotes (exact search) it fails: https://dev.kohesio.eu/projects?keywords=%22ai%22

**Comment by D063520** [comment]
It comes from the other languages ... you remember that they wanted that we search over all languages in the case there is something wrongly translated ... this is a side effect ... we can discuss it tomorrow. On option is to just index in english

https://linkedopendata.eu/wiki/Item:Q1966554

BAKERY AGENT

ADDETTO AI PRODOTTI DA FORNO

**Comment by madewild** [comment]
Oh, I wouldn't have guessed! Alright, let's discuss tomorrow.

**Comment by madewild** [comment]
Just an idea: would it be difficult to search over all languages ONLY when using quotes?

**Comment by madewild** [comment]
@AlyHdr : index only EN, remove other languages
