### ISSUE TITLE
Backslash ignored by export

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#34]
See https://linkedopendata.eu/wiki/Item:Q77445 for instance

**Comment by madewild** [comment]
Not so urgent, let's focus on other issues first

**Comment by AlyHdr** [comment]
We fixed this already but it's not deployed yet..

**Comment by D063520** [comment]
The initial example is not there anymore since the text was retranslated, but the error should be gone .... added to this entity a backslash:

https://linkedopendata.eu/wiki/Item:Q2100851

to be removed after the expert tomorrow is checked

**Comment by D063520** [comment]
@AlyHdr: now the backslash disappered, but it should stay .....
