### ISSUE TITLE
Czechia

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#35]
vs Czech Republic, what does the MS prefer?

**Comment by madewild** [comment]
So we should use Czechia everywhere instead of Czech Republic... let's start in the Countries filter, and also sort the countries alphabetically while we're at it :)

**Comment by madewild** [comment]
For the Wikibase it can wait...

**Comment by madewild** [comment]
Maybe this can also wait, let's not risk breaking the API/UI just before the merge

**Comment by madewild** [comment]
Confirmed by Anne, we should change to Czechia everywhere

**Comment by D063520** [comment]
Hi Max,

this should be fine, except that the country entity is still colled Czech Republic. Do we want to change this too?

It's a bit hard to change the name of an entity imported from Wikidata ... and to keep it in sync like this ...

Salut
Dennis

**Comment by madewild** [comment]
OK let's keep it like that for now, maybe Wikidata/Wikipédia will also finally change
https://www.wikidata.org/wiki/Talk:Q213
https://en.wikipedia.org/wiki/Talk:Czech_Republic

**Comment by D063520** [comment]
Maybe you can put a comment as a member from the commission to move them towards it ; )
