### ISSUE TITLE
Export improvements

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#36]
Not urgent but to keep some notes on exports:

- beneficiaries are based on string (P841) rather than disambiguated entity (P889). Therefore the total number is always different from the one show on the Kohesio homepage. One option would be to include the label of P889 in the export (keeping in mind that it is not translated in English, so we need to adapt language from country to country)
- NUTS3 code is not always the most relevant (for Italy for instance it refers to provinces rather than regions) so it could be useful to include all NUTS codes in the export (in distinct columns)

**Comment by D063520** [comment]
would it be fine if I make a separate export for the nuts, 4 columns, nuts3, nuts2 nuts1, country. I think it can be joint in the click thing tool ....

otherwise making the join will unnecessary increase the export ....

**Comment by madewild** [comment]
QlikSense ;)
Yes I guess it would also work like this...

**Comment by madewild** [comment]
Catia confirms it's fine (of course we also need the QID). Do you want me to do it? A single export is fine, we don't need to update this every day
For the beneficiaries let's think what is best

**Comment by madewild** [comment]
Example for France:
https://query.linkedopendata.eu/#select%20%3Fproject%20%3Fnuts3%20%3Fnuts2%20%3Fnuts1%20%3Fcountry%20where%20%7B%0A%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ9934%3E%20.%0A%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP32%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ20%3E%20.%0A%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3Fn3%20.%0A%3Fn3%20rdfs%3Alabel%20%3Fnuts3%20FILTER%28lang%28%3Fnuts3%29%20%3D%20%27en%27%29%0A%3Fn3%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3Fn2%20.%0A%3Fn2%20rdfs%3Alabel%20%3Fnuts2%20FILTER%28lang%28%3Fnuts2%29%20%3D%20%27en%27%29%0A%3Fn2%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3Fn1%20.%0A%3Fn1%20rdfs%3Alabel%20%3Fnuts1%20FILTER%28lang%28%3Fnuts1%29%20%3D%20%27en%27%29%0A%3Fn1%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3Fn0%20.%0A%3Fn0%20rdfs%3Alabel%20%3Fcountry%20FILTER%28lang%28%3Fcountry%29%20%3D%20%27en%27%29%0A%7D

**Comment by madewild** [comment]
Done for all countries except Italy for which there is a timeout, will try again later

https://query.linkedopendata.eu/#select%20%3Fproject%20%3Fnuts3%20%3Fnuts2%20%3Fnuts1%20%3Fcountry%20where%20%7B%0A%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ9934%3E%20.%0A%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP32%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ15%3E%20.%0A%3Fproject%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3Fn3%20.%0A%3Fn3%20rdfs%3Alabel%20%3Fnuts3%20FILTER%28lang%28%3Fnuts3%29%20%3D%20%27en%27%29%0A%3Fn3%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3Fn2%20.%0A%3Fn2%20rdfs%3Alabel%20%3Fnuts2%20FILTER%28lang%28%3Fnuts2%29%20%3D%20%27en%27%29%0A%3Fn2%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3Fn1%20.%0A%3Fn1%20rdfs%3Alabel%20%3Fnuts1%20FILTER%28lang%28%3Fnuts1%29%20%3D%20%27en%27%29%0A%3Fn1%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP1845%3E%20%3Fn0%20.%0A%3Fn0%20rdfs%3Alabel%20%3Fcountry%20FILTER%28lang%28%3Fcountry%29%20%3D%20%27en%27%29%0A%7D

**Comment by D063520** [comment]
they are also available here now:

https://data.linkedopendata.eu/kohesio/

**Comment by madewild** [comment]
My query above for Italy is still failing with Error code: SIGTRAP. @D063520 can you run it on the other endpoint?
I saw your nuts exports but they do not contain one line per project so I need to check with Catia if she could reconcile that with what she already haves (the other exports do not have qids of region, only region label which can be ambiguous, so it's better to reconcile files on project qid).
Also, we still need to decide what to do about beneficiaries (label of P889 ?)

**Comment by D063520** [comment]
I would prefer putting in the project export an identifier for regions and one for beneficiaries and then have two separate files: one with the details for the regions (like it is right now) and one with the details for the beneficiaries .... I think this would be a proper more SQL like export .... is this fine?

**Comment by madewild** [comment]
OK for me
