### ISSUE TITLE
Projects not showing on the map

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#37]
https://kohesio.eu/projects?keywords=green%20carbon&country=France

there is nothing on the map and an error (ERROR TypeError: e.forEach is not a function) in the console

**Comment by madewild** [comment]
The query above works, but this one still fails: https://kohesio.eu/projects?keywords=green&country=France

We get a 500 error:

message: "Http failure response for https://kohesio.linkedopendata.eu/api/facet/eu/search/project/map?keywords=green&country=https://linkedopendata.eu/entity/Q20&granularityRegion=https://linkedopendata.eu/entity/Q20: 500 OK"
name: "HttpErrorResponse"
ok: false
status: 500
statusText: "OK"
url: "https://kohesio.linkedopendata.eu/api/facet/eu/search/project/map?keywords=green&country=https://linkedopendata.eu/entity/Q20&granularityRegion=https://linkedopendata.eu/entity/Q20"

**Comment by D063520** [comment]
ok, I changed something .... in general on the map there is a SPARQL query optimization problem .... we have this in mind, we have an idea how to fix it, but to implement it will take some time ..... cannot do better currently
