### ISSUE TITLE
Fake id does not return an error

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-backend#43]
An example:

https://kohesio.linkedopendata.eu/api/dev/facet/eu/project?id=https://linkedopendata.eu/entity/fakeid

It is possible return an error: 500, for example, instead of all empty?

**Comment by AlyHdr** [comment]
https://kohesio.linkedopendata.eu/api/dev/facet/eu/project?id=https://linkedopendata.eu/entity/fakeid

This returns a 404 bad request now - as well as for the beneficiary
