### ISSUE TITLE
Export beneficiaries (and project) to XLSX

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#44]
Not XLS :) In the UI

**Comment by D063520** [comment]
move this to the UI

**Comment by madewild** [comment]
@D063520 the export button works on both projects and beneficiaries but the output is still in XLS, should be in **XLSX**, thanks

**Comment by D063520** [comment]
It's related to this:

https://github.com/ec-doris/kohesio.eu/issues/151#issuecomment-729674301

it's a front-end problem, not a back-end problem ... can you check again, Raph seams to have fixed it

**Comment by madewild** [comment]
ok sorry
