### ISSUE TITLE
Wikidata beneficiary served in wrong language

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#47]
https://kohesio.eu/projects/Q190314

beneficiary
Name: Korsikas forvaltning (https://www.wikidata.org/wiki/Q17050) in Danish (?!) instead of French

on https://linkedopendata.eu/wiki/Item:Q190314 it's displayed correctly in French ("Collectivité de Corse")

**Comment by D063520** [comment]
working on dev:

https://dev.kohesio.eu/projects/Q190314
