### ISSUE TITLE
Invalid (end) date

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#49]
Example: https://kohesio.eu/projects/Q19824
The end date is invalid. However on https://linkedopendata.eu/wiki/Item:Q19824 we see an "expected end time". We should probably have something smarter in the UI for unfinished projects than showing "invalid end date" for all ;)

**Comment by AlyHdr** [comment]
Now it's working on DEV: https://dev.kohesio.eu/projects?keywords=olive%20tree
