### ISSUE TITLE
Missing end date

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#54]
On https://kohesio.eu/beneficiaries/Q198964 we have "Invalid date" for both start and end date. However the only project linked to this beneficiary actually has an end date: https://kohesio.eu/projects/Q11724. On the project detail page it comes from "expected end time" but not on the beneficiary detail page.

**Comment by D063520** [comment]
So you would like to keep the start date as invalid and the end date as expected end date?

**Comment by madewild** [comment]
Yes the start date as Unknown (cf. #55 ) and the end date linked to expected end date of the project to be aligned with the project detail page
