### ISSUE TITLE
strange 404

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-backend#56]
check ... third entry https://dev.kohesio.eu/projects?keywords=angola

**Comment by D063520** [comment]
is this in the dump of semantic search? https://linkedopendata.eu/entity/Q2511130

**Comment by madewild** [comment]
Strange, it's a beneficiary and should not be retrivable from project search...

**Comment by madewild** [comment]
https://linkedopendata.eu/wiki/Item:Q2511130

**Comment by D063520** [comment]
we will check if we put it by mistake in the dump we provided .....

**Comment by dylanjcastillo** [comment]
HI @D063520, I just checked in the dump and it's available there. Here's the data associated with that entry: 
<img width="673" alt="image" src="https://user-images.githubusercontent.com/7218756/114994864-86968e80-9e9d-11eb-9c26-9adba9ee2f77.png">

**Comment by D063520** [comment]
ok, then we made a mistake .... ahhh yes, I know what happened ... I used the same query that we use to index the data in lucene. And we want to index also the beneficiaries since we need them for the "beneficiary search". Then at query time, we filter out only the projects ..... we will share with you another dump ....

**Comment by madewild** [comment]
Maybe later we will want semantic search for beneficiary search as well, so let's think if it's easier to continue with the filter at query time or to provide two separate dumps (and then 2 different ES indexes)...

**Comment by D063520** [comment]
I think semantic search on the beneficiary is not a good idea .... imagine you search for "ibm" and he returns "google" or "facebook" .... that is really not what the user wants

**Comment by madewild** [comment]
Yes true, good point!
