### ISSUE TITLE
Don't overwrite labels (e.g. Czechia)

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#63]
When hovering over the map on the homepage, it still says "Czech Republic - 46 258 projects"
Should be changed to Czechia as elsewhere

**Comment by madewild** [comment]
so @D063520 basically we cannot really fix this in a clean way while the Wikidata label "Czech Republic"?
if that's the case we can close for now

**Comment by D063520** [comment]
Hola, so it is possible but not super easy .... please let it open ...

**Comment by madewild** [comment]
ok, postponed then

**Comment by madewild** [comment]
Same for Ireland vs Republic of Ireland, etc.

**Comment by D063520** [comment]
This issue
https://github.com/the-qa-company/WikibaseSync/issues/8
was solved and labels modified in the Wikibase have now priority over labels changes in Wikidata
