### ISSUE TITLE
Country code null on beneficiaries list

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio-backend#66]
Sometimes we have a country code null in the beneficiaries list

![image](https://user-images.githubusercontent.com/5124917/124568313-11f04200-de45-11eb-8b7b-e68ad31e8d6d.png)

**Comment by madewild** [comment]
I see this beneficiary (https://linkedopendata.eu/wiki/Item:Q2532515) has been merged into https://linkedopendata.eu/wiki/Item:Q1090
so I guess it should be removed from the list

**Comment by D063520** [comment]
We should not remove it .... we should attach the projects to beneficary Q1090 instead of Q2532515 .... need to make a script for this ...

**Comment by D063520** [comment]
there are exactly 103 such cases ...

https://query.linkedopendata.eu/#select%20%2a%20where%20%7B%0A%20%20%3Fs1%20%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ9934%3E%20.%0A%20%20%3Fs1%20%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP889%3E%20%20%3Fo2%20.%20%0A%20%20%3Fo2%20owl%3AsameAs%20%3Fo%20.%20%20%20%20%20%0A%7D

so luck Raph ; )

**Comment by D063520** [comment]
ok, the script run through ... we can check tomorrow after reindexing ....

**Comment by madewild** [comment]
@raphdom do you still see such cases or can we close?

**Comment by raphdom** [comment]
everything is fine now, we can close it
