### ISSUE TITLE
Unprecise regionText for Greek projects

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#67]
https://dev.kohesio.eu/projects/Q2814985 says "In Greece" over the map
The API sends "regionText":"Greece" but it should be "regionText":"Κεντρική Μακεδονία, Greece" or similar (not sure if we include "Northern Greece" as it's statistical only)
it's correct on https://linkedopendata.eu/wiki/Item:Q2814985

**Comment by D063520** [comment]
I did not check ... but I'm pretty sure the problem is that for greece we do not have nuts 3, but only nuts 2 .....

**Comment by AlyHdr** [comment]
This should be fine now you can check the project that @madewild pointed out: https://dev.kohesio.eu/projects/Q2814985
