### ISSUE TITLE
Allow to filter beneficiaries by public/private

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#72]
It's in the wikibase but not exposed in the API.
Then move the issue to UI for Raph

**Comment by madewild** [comment]
@AlyHdr this could be a quick win, it's at the same level as the beneficiary per fund you just created...

**Comment by AlyHdr** [comment]
On this we need some specific query from the SPARQL endpoint which has for now only the truthy statements from the wikibase. So basically we still don't have this probably for the next release..

**Comment by madewild** [comment]
Yes, I realised and already moved to v0.9 :)

**Comment by madewild** [comment]
@AlyHdr are you ready for this?
@raphdom is waiting for this to implement https://github.com/ec-doris/kohesio.eu/issues/258

**Comment by AlyHdr** [comment]
This was implemented since some time now, however it's not working because we are not using the wikibase endpoint. We will try to index all statements from the wikibase, will update you on this once we have the full index.

**Comment by D063520** [comment]
@AlyHdr I remember that the problem was that the reefied statements are not there ... this is not the case anymore

**Comment by AlyHdr** [comment]
Yes the filter is done by passing beneficiaryType={public or private}, example:

https://dev.kohesio.linkedopendata.eu/api/facet/eu/search/beneficiaries?offset=0&limit=15&country=https://linkedopendata.eu/entity/Q25&beneficiaryType=private

**Comment by madewild** [comment]
Excellent, so this is working on the backend side and can move forward to the UI, right?
