### ISSUE TITLE
Semantic Search (Trim function)

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#75]
Hi guys, 

just noticed that if the keyword is preceded by a black space, the search is no giving back any result.
Maybe we could add a sort of trim function on the keyword so to remove all non trailing spaces. 
I leave it to you to see if and when we want to tackle this.  

![image](https://user-images.githubusercontent.com/86654885/134870287-9c294d59-1308-421b-9091-548d316eafc3.png)

**Comment by madewild** [comment]
https://dev.kohesio.eu/projects?keywords=%20reducing%20coastal%20erosion

**Comment by madewild** [comment]
Trailing spaces are not causing this issue (see https://dev.kohesio.eu/projects?keywords=reducing%20coastal%20erosion%20), only leading spaces.

**Comment by AlyHdr** [comment]
It should be fixed. Let me know if there are other problems like this.
