### ISSUE TITLE
Index EN only for search engine

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#76]
@AlyHdr : index only EN, remove other languages

_Originally posted by @madewild in https://github.com/ec-doris/kohesio-backend/issues/30#issuecomment-926487650_

**Comment by AlyHdr** [comment]
@D063520 We need to change the query for the Lucene index.

**Comment by D063520** [comment]
Sorry, I forgot about this. I changed it, but it will be ready only from tomorrow ....

**Comment by madewild** [comment]
Perfect, as long as it's ready for Thursday's merge. :)
