### ISSUE TITLE
Return all geometries

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#77]
https://dev.kohesio.eu/projects/Q86132

**Comment by madewild** [comment]
+ change label over map

**Comment by AlyHdr** [comment]
The API returns a list of geoJson and the coordinates, the label is now "regionText": "In multiple locations, Poland".

https://dev.kohesio.linkedopendata.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q86132

**Comment by madewild** [comment]
Oops, this is a breaking change so all project detail pages return a 404 now!!
We need @raphdom to fix this on the UI unless you revert...

**Comment by madewild** [comment]
@AlyHdr sorry the regionText should just be "multiple locations, Poland" because now we have a double "in"!
https://dev.kohesio.eu/projects/Q86132

**Comment by AlyHdr** [comment]
This is working!
