### ISSUE TITLE
AND vs OR

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#8]
Search with two words (e.g. low carbon) should give higher score to projects with both words

**Comment by D063520** [comment]
This also seams to work:

https://dev.kohesio.eu/projects?country=Czech-Republic&keywords=management%20AND%20tracking

https://dev.kohesio.eu/projects?country=Czech-Republic&keywords=management%20OR%20tracking

This is what we want or?

**Comment by madewild** [comment]
Yes perfect, we just need to document somewhere for the users that AND should be spelled in capitals for the intersection (OR is default behaviour). We can document the * for wildcard at the same place
