### ISSUE TITLE
Wrong "multiple locations"

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#83]
On https://kohesio.eu/projects/Q3102435 it says "In multiple locations, Luxembourg" (also in the api response).
But https://linkedopendata.eu/wiki/Item:Q3102435 only has a single location...

**Comment by AlyHdr** [comment]
It's fixed on dev now: https://dev.kohesio.eu/projects/Q3102435, we can merge it with prod if you want or wait for the next iteration.

**Comment by madewild** [comment]
thx, it can wait for the merge
