### ISSUE TITLE
Send multiple categoryLabel and objectiveLabel

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#85]
https://linkedopendata.eu/wiki/Item:Q9779 has two intervention fields

but https://dev.kohesio.linkedopendata.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q9779 only retrieves one ("categoryLabel":"Research and innovation processes in SMEs (including voucher schemes, process, design, service and social innovation)") we should allow several to display in the UI (cf. https://github.com/ec-doris/kohesio.eu/issues/256)

same thing for multiple thematic objectives...

**Comment by D063520** [comment]
@AlyHdr @DiaZork could you check this together please so that Jonathan learns what is going on ...

**Comment by AlyHdr** [comment]
This is implemented, now we have lists (categoryLabels, objectiveLabels and objectiveIds):
https://dev.kohesio.linkedopendata.eu/api/facet/eu/project?id=https://linkedopendata.eu/entity/Q9779

This can move to  ec-doris/kohesio.eu#256. @raphdom
