### ISSUE TITLE
point api seams to be broken

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio-backend#89]
<img width="1680" alt="Screenshot 2021-12-12 at 20 44 06" src="https://user-images.githubusercontent.com/10883585/145727108-51882805-ea7e-4bc3-ab24-b5ea3118a38f.png">

**Comment by D063520** [comment]
to check in the morning, maybe it was becasue the sparql endpoint started indexing

**Comment by madewild** [comment]
I don't see any problem, the indexing started at the time you posted but now all is fine.
