### ISSUE TITLE
Missing Slovene beneficiary names

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#92]
![slovenia](https://user-images.githubusercontent.com/942488/146752662-50796c93-f405-4654-a5f0-6ff0551a96f7.png)

**Comment by AlyHdr** [comment]
This is fixed now but I found out that there are other countries like Lithuania and Finland.. Lithunia is good now as well, however in Finland upon import we took the language code of the spoken language like so:

https://query.linkedopendata.eu/#select%20%20%2a%20where%20%7B%0A%20%20%20%20%20%20%20%20%20%20values%20%3Fcountry%20%7B%20wd%3AQ10%20%7D%0A%20%20%20%20%20%20%20%20%20%20%3Fcountry%20wdt%3AP19%20%3Flanguage%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Flanguage%20wdt%3AP654%20%3Fcode%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Fcountry%20rdfs%3Alabel%20%3Flabel%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20filter%28lang%28%3Flabel%29%20%3D%20%27en%27%29%0A%20%20%20%20%20%20%20%20%7D

And basically the one taken was Sweden by accident and not Finnish, so I will update the data to change the labels to Finnish.

**Comment by AlyHdr** [comment]
Finnish beneficiaries appear now:
https://dev.kohesio.eu/beneficiaries?country=Finland
