### ISSUE TITLE
Beneficiary fiche does not display beneficiary name

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#93]
Hi guys, I noticed that in Lithuania the beneficiary fiche does not display beneficiary name.
 In general, data from Lithuania are partial but beneficiary information are present.

I am not sure if this is a front end or backend problem, but I can't check the latter because dev is down :( 

https://kohesio.eu/beneficiaries/Q3818845

![image](https://user-images.githubusercontent.com/86654885/147065212-8e5408a6-b853-4cd9-b575-9c06c0c77563.png)

**Comment by madewild** [comment]
I'm pretty sure it's linked to #92 
@AlyHdr can you have a look?

**Comment by AlyHdr** [comment]
This should be fixed on DEV, we can test once the index is available

**Comment by AlyHdr** [comment]
Label is appearing now: https://dev.kohesio.eu/beneficiaries/Q3818845
