### ISSUE TITLE
Sweden ERDF projects

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio-backend#94]
Kohesio.eu 
I noticed that if you search for ERDF projects and show the map, Sweden is in grey altough it has ERDF projects. (see screenshot 1)

If you then select Sweden in the country filter, projects are shown (see screenshot 2)

------
Screenshot 1

![image](https://user-images.githubusercontent.com/86654885/147067346-a51637b6-8a3e-4eac-a234-7cb48b380fb7.png)

------
Screenshot 2

![image](https://user-images.githubusercontent.com/86654885/147067210-268d4df2-e690-4325-9461-37296a972a14.png)

**Comment by madewild** [comment]
Very strange... @AlyHdr can you investigate what is happening?

**Comment by D063520** [comment]
very strange ... I clean the cache file for that query and now it works ..... maybe some old cache file ....
