### ISSUE TITLE
Add transliteration to beneficiary detail page api

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#96]
Currently we already have the transliteration on https://dev.kohesio.linkedopendata.eu/api/facet/eu/search/beneficiaries?offset=0&limit=15&country=https://linkedopendata.eu/entity/Q31

But we would also need it on https://dev.kohesio.linkedopendata.eu/api/facet/eu/beneficiary?id=https://linkedopendata.eu/entity/Q2748683 for instance (only once for the beneficiary, not for every project!)

@DiaZork can you take care of this? Prerequisite for https://github.com/ec-doris/kohesio.eu/issues/299

**Comment by DiaZork** [comment]
This is done too
