### ISSUE TITLE
Transliteration should not appear if English label displayed

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#99]
There is a minor issue for Cyprus that should be fixed in the backend, some transliterations are displayed although the name is en English: https://dev.kohesio.eu/beneficiaries?country=Cyprus
![cy_translit](https://user-images.githubusercontent.com/942488/151441380-d512fc52-8d9f-4506-9f62-91ed686a5e05.png)

_Originally posted by @madewild in https://github.com/ec-doris/kohesio.eu/issues/299#issuecomment-1023626887_

**Comment by madewild** [comment]
@DiaZork we should adapt the sparql query a bit...

**Comment by DiaZork** [comment]
It's fixed
